name: API and Performance Testing CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  JAVA_VERSION: "17"
  ALLURE_VERSION: "2.19.0"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'

      - name: Cache Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Run Functional Tests
        run: mvn clean verify

      - name: Run Performance Tests (Gatling)
        run: mvn gatling:test

      - name: Upload Allure Results
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: target/allure-results

      - name: Upload Gatling Report
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: gatling-report
          path: target/gatling

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Download Allure Results
        uses: actions/download-artifact@v3
        with:
          name: allure-results
          path: allure-results

      - name: Download Gatling Report
        uses: actions/download-artifact@v3
        with:
          name: gatling-report
          path: gatling-report

      - name: Debug: List downloaded artifacts
        run: |
          echo "Allure Results:"
          ls -R allure-results
          echo "Gatling Report:"
          ls -R gatling-report

      - name: Install Allure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          wget https://github.com/allure-framework/allure2/releases/download/${{ env.ALLURE_VERSION }}/allure-${{ env.ALLURE_VERSION }}.zip
          unzip allure-${{ env.ALLURE_VERSION }}.zip -d /opt/allure
          sudo ln -s /opt/allure/allure-${{ env.ALLURE_VERSION }}/bin/allure /usr/bin/allure

      - name: Generate Allure Report
        run: allure generate allure-results -o reports/cucumber --clean

      - name: Prepare Reports Index
        run: |
          mkdir -p reports
          echo "<!DOCTYPE html>" > reports/index.html
          echo "<html><head><title>Test Reports</title></head><body>" >> reports/index.html
          echo "<h1>Test Reports</h1><ul>" >> reports/index.html
          echo "<li><a href=\"cucumber/index.html\">Cucumber Report</a></li>" >> reports/index.html
          # Find the Gatling report index.html
          GATLING_REPORT=$(find gatling-report -name "index.html" | head -n 1)
          echo "Gatling report found at: $GATLING_REPORT"
          # Extract directory of the report
          REPORT_DIR=$(dirname $GATLING_REPORT)
          REPORT_BASENAME=$(basename $REPORT_DIR)
          mkdir -p reports/gatling
          cp -r $REPORT_DIR reports/gatling/
          # Now reports/gatling/REPORT_BASENAME/index.html should exist
          echo "<li><a href=\"gatling/${REPORT_BASENAME}/index.html\">Gatling Report</a></li>" >> reports/index.html
          echo "</ul></body></html>" >> reports/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: reports
