name: API and Performance Testing CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step: Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step: Set up JDK 17 for the build environment
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step: Cache Maven dependencies to speed up builds
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step: Run Cucumber tests to verify API functionality
      - name: Run Cucumber tests
        run: mvn clean verify

      # Step: Run Gatling tests for performance and load testing
      - name: Run Gatling tests
        run: mvn gatling:test

      # Step: Install Allure CLI to generate reports
      - name: Install Allure CLI
        run: |
          sudo apt update
          sudo apt install -y allure

      # Step: Generate Allure report for Cucumber tests
      - name: Generate Allure report
        run: |
          allure generate target/allure-results -o reports/cucumber

      # Step: Create an index.html file with links to test reports
      - name: Prepare reports index
        run: |
          mkdir -p reports
          echo "<!DOCTYPE html>" > reports/index.html
          echo "<html><head><title>Test Reports</title></head><body>" >> reports/index.html
          echo "<h1>Test Reports</h1><ul>" >> reports/index.html
          echo "<li><a href=\"cucumber/index.html\">Cucumber Report</a></li>" >> reports/index.html
          GATLING_REPORT=$(find target/gatling -name "index.html" | head -n 1)
          echo "<li><a href=\"gatling/$(basename $(dirname $GATLING_REPORT))/index.html\">Gatling Report</a></li>" >> reports/index.html
          echo "</ul></body></html>" >> reports/index.html

      # Step: Deploy test reports to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: reports
